// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0IjFZUWc8vUwkSy25jvb9LYzdIjN-P5E',
    appId: '1:1083565489838:web:120539c3c6cb355008773f',
    messagingSenderId: '1083565489838',
    projectId: 'birdiefy-app',
    authDomain: 'birdiefy-app.firebaseapp.com',
    storageBucket: 'birdiefy-app.appspot.com',
    measurementId: 'G-GB93HQPVN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCHWngUcAvm_pfQastBEabbhtF8sih0Y',
    appId: '1:1083565489838:android:80541dc9115f0f8808773f',
    messagingSenderId: '1083565489838',
    projectId: 'birdiefy-app',
    storageBucket: 'birdiefy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyhhWoWk5EqUPjzHiTkDJOfs9RijdQAuE',
    appId: '1:1083565489838:ios:1de79e815ac81fa508773f',
    messagingSenderId: '1083565489838',
    projectId: 'birdiefy-app',
    storageBucket: 'birdiefy-app.appspot.com',
    iosClientId: '1083565489838-e0d9cal6k9ujhfm7oko1efvn06jr1171.apps.googleusercontent.com',
    iosBundleId: 'com.example.birdiefy',
  );
}
